import type {
  Candidate, HiringProcess, JobDescription, ProcessCandidate,
  KanbanResponse, QuestionSet, ProfilingRun, AIModelConfig,
  AIPrompt, MetricsDashboard,
} from './types';

// ─── Tipos extendidos para dual match ────────────────────────────────────────
export interface DualMatchCandidate extends ProcessCandidate {
  cv_match_percentage: number;
  cv_match_category: 'HIGH' | 'MEDIUM' | 'LOW';
  cv_match_explanation: {
    strengths: string[];
    gaps: string[];
    summary: string;
    risk_flags?: string[];
  };
}

export interface DualKanbanResponse {
  HIGH: DualMatchCandidate[];
  MEDIUM: DualMatchCandidate[];
  LOW: DualMatchCandidate[];
  LOADED: DualMatchCandidate[];
  PARSING: DualMatchCandidate[];
}

// ─── Candidatos ──────────────────────────────────────────────────────────────
export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'cand-001',
    name: 'Andres Felipe',
    last_name: 'Moreno Torres',
    email: 'andres.moreno@gmail.com',
    phone: '+57 312 456 7890',
    cv_file_url: '/cvs/andres_moreno.pdf',
    extracted_profile: { years_experience: 7, main_tech: ['Java', 'Spring Boot', 'Kubernetes'] },
    created_at: '2025-06-01T09:00:00Z',
    updated_at: '2025-06-10T14:30:00Z',
  },
  {
    id: 'cand-002',
    name: 'Maria Camila',
    last_name: 'Rodriguez Ospina',
    email: 'camila.rodriguez@hotmail.com',
    phone: '+57 315 789 0123',
    cv_file_url: '/cvs/camila_rodriguez.pdf',
    extracted_profile: { years_experience: 6, main_tech: ['Java', 'Microservicios', 'AWS'] },
    created_at: '2025-06-01T10:15:00Z',
    updated_at: '2025-06-10T15:00:00Z',
  },
  {
    id: 'cand-003',
    name: 'Juan Sebastian',
    last_name: 'Gomez Arias',
    email: 'sebastian.gomez@outlook.com',
    phone: '+57 316 234 5678',
    cv_file_url: '/cvs/sebastian_gomez.pdf',
    extracted_profile: { years_experience: 5, main_tech: ['React', 'TypeScript', 'Next.js'] },
    created_at: '2025-06-02T08:30:00Z',
    updated_at: '2025-06-11T09:00:00Z',
  },
  {
    id: 'cand-004',
    name: 'Laura Valentina',
    last_name: 'Herrera Castillo',
    email: 'laura.herrera@gmail.com',
    phone: '+57 317 345 6789',
    cv_file_url: '/cvs/laura_herrera.pdf',
    extracted_profile: { years_experience: 4, main_tech: ['React', 'Vue.js', 'Figma'] },
    created_at: '2025-06-02T11:00:00Z',
    updated_at: '2025-06-11T10:30:00Z',
  },
  {
    id: 'cand-005',
    name: 'Diego Alejandro',
    last_name: 'Vargas Perez',
    email: 'diego.vargas@yahoo.com',
    phone: '+57 318 456 7890',
    cv_file_url: '/cvs/diego_vargas.pdf',
    extracted_profile: { years_experience: 8, main_tech: ['Python', 'Spark', 'Airflow', 'Kafka'] },
    created_at: '2025-06-03T09:45:00Z',
    updated_at: '2025-06-12T11:00:00Z',
  },
  {
    id: 'cand-006',
    name: 'Daniela Paola',
    last_name: 'Gutierrez Lopez',
    email: 'daniela.gutierrez@gmail.com',
    phone: '+57 319 567 8901',
    cv_file_url: '/cvs/daniela_gutierrez.pdf',
    extracted_profile: { years_experience: 3, main_tech: ['Python', 'dbt', 'BigQuery'] },
    created_at: '2025-06-03T14:00:00Z',
    updated_at: '2025-06-12T12:30:00Z',
  },
  {
    id: 'cand-007',
    name: 'Carlos Eduardo',
    last_name: 'Ramirez Sanchez',
    email: 'carlos.ramirez@outlook.com',
    phone: '+57 300 678 9012',
    cv_file_url: '/cvs/carlos_ramirez.pdf',
    extracted_profile: { years_experience: 6, main_tech: ['Scrum', 'OKRs', 'Roadmapping', 'Fintech'] },
    created_at: '2025-06-04T08:00:00Z',
    updated_at: '2025-06-13T09:30:00Z',
  },
  {
    id: 'cand-008',
    name: 'Natalia Isabel',
    last_name: 'Reyes Mendoza',
    email: 'natalia.reyes@gmail.com',
    phone: '+57 301 789 0123',
    cv_file_url: '/cvs/natalia_reyes.pdf',
    extracted_profile: { years_experience: 2, main_tech: ['Figma', 'Adobe XD', 'User Research'] },
    created_at: '2025-06-04T10:30:00Z',
    updated_at: '2025-06-13T11:00:00Z',
  },
  {
    id: 'cand-009',
    name: 'Santiago Andres',
    last_name: 'Jimenez Rueda',
    email: 'santiago.jimenez@hotmail.com',
    phone: '+57 302 890 1234',
    cv_file_url: '/cvs/santiago_jimenez.pdf',
    extracted_profile: { years_experience: 4, main_tech: ['Java', 'Node.js', 'PostgreSQL'] },
    created_at: '2025-06-05T09:00:00Z',
    updated_at: '2025-06-14T10:00:00Z',
  },
  {
    id: 'cand-010',
    name: 'Valentina Sofia',
    last_name: 'Morales Quintero',
    email: 'valentina.morales@gmail.com',
    phone: '+57 303 901 2345',
    cv_file_url: '/cvs/valentina_morales.pdf',
    extracted_profile: { years_experience: 3, main_tech: ['React', 'Angular', 'Tailwind CSS'] },
    created_at: '2025-06-05T11:00:00Z',
    updated_at: '2025-06-14T12:00:00Z',
  },
];

// ─── Procesos ─────────────────────────────────────────────────────────────────
export const MOCK_PROCESSES: HiringProcess[] = [
  {
    id: 'proc-001',
    name: 'Ingeniero Backend Senior - Q3 2025',
    job_title: 'Senior Backend Engineer',
    area: 'Tecnologia',
    seniority: 'Senior',
    status: 'PROFILING_CONFIGURED',
    budget_max_usd: 80,
    recruiter_id: 'user-001',
    question_set_id: 'qs-001',
    created_at: '2025-05-28T08:00:00Z',
    updated_at: '2025-06-15T16:00:00Z',
  },
  {
    id: 'proc-002',
    name: 'Desarrollador Frontend React',
    job_title: 'Frontend Developer',
    area: 'Producto Digital',
    seniority: 'Semi-Senior',
    status: 'PROFILING_CONFIGURED',
    budget_max_usd: 60,
    recruiter_id: 'user-001',
    question_set_id: 'qs-002',
    created_at: '2025-06-01T09:00:00Z',
    updated_at: '2025-06-16T10:00:00Z',
  },
  {
    id: 'proc-003',
    name: 'Data Engineer - Pipeline Analytics',
    job_title: 'Data Engineer',
    area: 'Analytics',
    seniority: 'Senior',
    status: 'MATCHING',
    budget_max_usd: 70,
    recruiter_id: 'user-002',
    created_at: '2025-06-05T10:00:00Z',
    updated_at: '2025-06-17T08:30:00Z',
  },
  {
    id: 'proc-004',
    name: 'Product Manager - Fintech',
    job_title: 'Product Manager',
    area: 'Producto',
    seniority: 'Senior',
    status: 'READY_FOR_MATCH',
    budget_max_usd: 50,
    recruiter_id: 'user-001',
    created_at: '2025-06-10T14:00:00Z',
    updated_at: '2025-06-18T09:00:00Z',
  },
  {
    id: 'proc-005',
    name: 'UX/UI Product Designer',
    job_title: 'Product Designer',
    area: 'Diseno',
    seniority: 'Semi-Senior',
    status: 'DRAFT',
    budget_max_usd: 40,
    recruiter_id: 'user-002',
    created_at: '2025-06-18T11:00:00Z',
    updated_at: '2025-06-18T11:00:00Z',
  },
];

// ─── Job Descriptions ─────────────────────────────────────────────────────────
export const MOCK_JDS: Record<string, JobDescription> = {
  'proc-001': {
    id: 'jd-001',
    process_id: 'proc-001',
    version: 2,
    jd_raw_text: 'Buscamos un Ingeniero Backend Senior con solida experiencia en Java y ecosistema Spring para liderar el desarrollo de microservicios en produccion...',
    structured_jd: {
      must_have: [
        '5+ anos de experiencia con Java 11+ y Spring Boot',
        'Diseno e implementacion de microservicios',
        'Kubernetes y Docker en entornos productivos',
        'Bases de datos relacionales (PostgreSQL) y NoSQL (Redis/MongoDB)',
        'Diseno de APIs REST y experiencia con mensajeria (Kafka/RabbitMQ)',
      ],
      nice_to_have: [
        'Experiencia con Kotlin',
        'Certificaciones AWS o GCP',
        'Conocimiento en DDD y arquitectura hexagonal',
        'Experiencia liderando equipos de 3+ personas',
        'Contribuciones a proyectos open source',
      ],
      deal_breakers: [
        'Menos de 3 anos de experiencia total en backend',
        'Sin experiencia en entornos cloud (AWS/GCP/Azure)',
        'No haber trabajado con contenedores en produccion',
      ],
      weights: { must_have: 0.6, nice_to_have: 0.25, culture_fit: 0.15 },
      summary: 'Rol senior de backend con enfasis en arquitecturas distribuidas y liderazgo tecnico.',
    },
    created_at: '2025-06-01T10:00:00Z',
  },
  'proc-002': {
    id: 'jd-002',
    process_id: 'proc-002',
    version: 1,
    jd_raw_text: 'Buscamos un Desarrollador Frontend con React y TypeScript para construir interfaces de alta calidad en nuestros productos digitales...',
    structured_jd: {
      must_have: [
        '3+ anos con React y hooks modernos',
        'TypeScript avanzado (generics, utility types)',
        'Gestion de estado (Redux Toolkit o Zustand)',
        'Testing con Jest y React Testing Library',
        'Conocimiento profundo de CSS y sistemas de diseno',
      ],
      nice_to_have: [
        'Experiencia con Next.js 13+ (App Router)',
        'Storybook para documentacion de componentes',
        'Trabajo con equipos de diseno (Figma handoff)',
        'Conocimiento de Web Vitals y optimizacion de performance',
      ],
      deal_breakers: [
        'Sin experiencia con TypeScript',
        'Solo experiencia con Vue o Angular sin haber trabajado con React',
      ],
      weights: { must_have: 0.65, nice_to_have: 0.2, culture_fit: 0.15 },
      summary: 'Rol frontend con enfasis en calidad de codigo, testing y trabajo en equipo con diseno.',
    },
    created_at: '2025-06-03T14:00:00Z',
  },
  'proc-003': {
    id: 'jd-003',
    process_id: 'proc-003',
    version: 1,
    jd_raw_text: 'Buscamos un Data Engineer para construir y mantener pipelines de datos en nuestra plataforma de analytics...',
    structured_jd: {
      must_have: [
        '4+ anos construyendo pipelines de datos en Python',
        'Apache Spark o Flink para procesamiento distribuido',
        'Apache Airflow para orquestacion de workflows',
        'Experiencia con data warehouses (BigQuery, Snowflake o Redshift)',
        'SQL avanzado y optimizacion de consultas',
      ],
      nice_to_have: [
        'dbt para transformaciones SQL',
        'Kafka o Kinesis para streaming',
        'Conocimientos de MLOps',
        'Experiencia con Terraform',
      ],
      deal_breakers: [
        'Sin experiencia con Python para ingenieria de datos',
        'Experiencia unicamente en BI sin pipelines productivos',
      ],
      weights: { must_have: 0.7, nice_to_have: 0.2, culture_fit: 0.1 },
      summary: 'Rol de ingenieria de datos con foco en plataformas de analytics en tiempo real.',
    },
    created_at: '2025-06-07T09:00:00Z',
  },
  'proc-004': {
    id: 'jd-004',
    process_id: 'proc-004',
    version: 1,
    jd_raw_text: 'Buscamos un Product Manager con experiencia en fintech para liderar el roadmap de nuestra plataforma de pagos...',
    structured_jd: {
      must_have: [
        '5+ anos como Product Manager en empresas de tecnologia',
        'Experiencia en sector fintech (pagos, credito o inversiones)',
        'Definicion y seguimiento de OKRs y KPIs de producto',
        'Metodologias agiles (Scrum/Kanban) en equipos de 8+ personas',
        'Capacidad de comunicar vision tecnica a stakeholders de negocio',
      ],
      nice_to_have: [
        'MBA o certificacion en Product Management',
        'Experiencia con regulacion financiera (SFC Colombia)',
        'Conocimientos basicos de SQL para analisis de datos',
        'Experiencia lanzando productos en mercados LATAM',
      ],
      deal_breakers: [
        'Sin experiencia directa en fintech o sector financiero',
        'Menos de 3 anos como PM (no en roles de soporte o BA)',
      ],
      weights: { must_have: 0.5, nice_to_have: 0.2, culture_fit: 0.3 },
      summary: 'PM senior para producto fintech con experiencia comprobada en pagos digitales.',
    },
    created_at: '2025-06-12T10:00:00Z',
  },
  'proc-005': {
    id: 'jd-005',
    process_id: 'proc-005',
    version: 1,
    jd_raw_text: 'Buscamos un Product Designer para crear experiencias de usuario de alta calidad en nuestra suite de productos...',
    structured_jd: {
      must_have: [
        '3+ anos en diseno de producto (UX/UI)',
        'Dominio avanzado de Figma (auto-layout, variables, componentes)',
        'Experiencia con sistemas de diseno (crear y mantener)',
        'User research y usability testing',
        'Portafolio demostrable con casos de estudio completos',
      ],
      nice_to_have: [
        'Conocimientos de frontend (HTML/CSS basico)',
        'Experiencia con motion design',
        'Certificacion en UX (Google, NN/g)',
        'Experiencia en productos B2B SaaS',
      ],
      deal_breakers: [
        'Sin portafolio con casos de estudio de proceso (solo mockups)',
        'Sin experiencia en diseno de producto (solo diseno grafico)',
      ],
      weights: { must_have: 0.6, nice_to_have: 0.2, culture_fit: 0.2 },
      summary: 'Designer de producto con enfasis en research, sistemas de diseno y calidad visual.',
    },
    created_at: '2025-06-18T11:00:00Z',
  },
};

// ─── Kanban (dual match) para proc-001 ───────────────────────────────────────
export const MOCK_KANBAN: Record<string, DualKanbanResponse> = {
  'proc-001': {
    HIGH: [
      {
        id: 'pc-001-001',
        process_id: 'proc-001',
        candidate_id: 'cand-001',
        status: 'SELECTED_FOR_PROFILING',
        match_percentage: 91,
        match_category: 'HIGH',
        match_explanation: {
          strengths: [
            'Respuestas claras y estructuradas sobre arquitectura de microservicios',
            'Demostro experiencia real liderando migraciones a Kubernetes',
            'Excelente fit cultural: orientado a resultados y trabajo en equipo',
          ],
          gaps: ['No menciono experiencia especifica con Kafka en la llamada'],
          summary: 'Candidato sobresaliente. La entrevista confirmo y supero el perfil del CV. Recomendado fuertemente.',
        },
        cv_match_percentage: 87,
        cv_match_category: 'HIGH',
        cv_match_explanation: {
          strengths: [
            '7 anos de experiencia con Java y Spring Boot en produccion',
            'Liderazgo tecnico demostrado en equipos de 5 personas',
            'Kubernetes y Docker en entornos de alta disponibilidad',
          ],
          gaps: [
            'No menciona experiencia con Kotlin',
            'Sin certificaciones cloud visibles en el CV',
          ],
          summary: 'Perfil muy solido. Cumple todos los must-have y 3 de 5 nice-to-have.',
        },
        human_notes: 'Llamada muy fluida. Conoce a fondo patrones DDD. Disponibilidad en 2 semanas.',
        created_at: '2025-06-10T08:00:00Z',
        updated_at: '2025-06-15T14:30:00Z',
        candidate: MOCK_CANDIDATES[0],
      },
      {
        id: 'pc-001-002',
        process_id: 'proc-001',
        candidate_id: 'cand-002',
        status: 'SELECTED_FOR_PROFILING',
        match_percentage: 84,
        match_category: 'HIGH',
        match_explanation: {
          strengths: [
            'Arquitectura cloud solida, describe ejemplos concretos en AWS',
            'Menciona haber reducido latencia en un 40% con optimizacion de queries',
            'Comunicacion tecnica muy clara con stakeholders',
          ],
          gaps: [
            'Experiencia con Kubernetes menor a la esperada (1 ano)',
            'No menciono gestion de equipos en la entrevista',
          ],
          summary: 'Candidata competente. La entrevista confirmo el nivel aunque con menos profundidad en Kubernetes.',
        },
        cv_match_percentage: 82,
        cv_match_category: 'HIGH',
        cv_match_explanation: {
          strengths: [
            '6 anos con Java, Spring Boot y arquitecturas de microservicios',
            'Experiencia comprobada con AWS (EC2, RDS, Lambda)',
            'Ha implementado patrones de resiliencia (Circuit Breaker, Saga)',
          ],
          gaps: [
            'Kubernetes mencionado pero con menos detalle que Java',
            'Sin experiencia documentada con Kafka o mensajeria async',
          ],
          summary: 'Perfil fuerte en backend Java y cloud. Cumple 4/5 must-have solidos.',
        },
        human_notes: 'Excelente presencia. Pregunto sobre cultura de PR reviews y CI/CD.',
        created_at: '2025-06-10T09:00:00Z',
        updated_at: '2025-06-15T15:00:00Z',
        candidate: MOCK_CANDIDATES[1],
      },
      {
        id: 'pc-001-009',
        process_id: 'proc-001',
        candidate_id: 'cand-009',
        status: 'SELECTED_FOR_PROFILING',
        match_percentage: 80,
        match_category: 'HIGH',
        match_explanation: {
          strengths: [
            'Buen nivel tecnico en Java y bases de datos',
            'Actitud proactiva y disposicion a aprender nuevas tecnologias',
            'Menciono proyectos personales con Kubernetes',
          ],
          gaps: [
            'Le costo explicar microservicios a nivel de arquitectura',
            'No tiene experiencia con mensajeria en produccion',
          ],
          summary: 'Candidato con buen potencial. La entrevista revela solidez en fundamentos aunque con algunas brechas en arquitectura avanzada.',
        },
        cv_match_percentage: 74,
        cv_match_category: 'MEDIUM',
        cv_match_explanation: {
          strengths: [
            '4 anos con Java y Spring, proyectos de mediana escala',
            'PostgreSQL y Redis con experiencia documentada',
          ],
          gaps: [
            'Kubernetes solo en proyectos personales, no en produccion',
            'Sin experiencia con mensajeria asincrona',
            'No menciona liderazgo tecnico',
          ],
          summary: 'Perfil solido en fundamentos pero con brechas en infraestructura cloud avanzada.',
        },
        created_at: '2025-06-10T10:00:00Z',
        updated_at: '2025-06-15T16:00:00Z',
        candidate: MOCK_CANDIDATES[8],
      },
    ],
    MEDIUM: [
      {
        id: 'pc-001-004',
        process_id: 'proc-001',
        candidate_id: 'cand-004',
        status: 'MATCHED',
        match_percentage: 68,
        match_category: 'MEDIUM',
        match_explanation: {
          strengths: [],
          gaps: [],
          summary: 'Pendiente de profiling.',
        },
        cv_match_percentage: 68,
        cv_match_category: 'MEDIUM',
        cv_match_explanation: {
          strengths: [
            'Conocimiento de Java y APIs REST',
            'Experiencia con bases de datos relacionales',
          ],
          gaps: [
            'Experiencia principalmente en frontend, backend limitado',
            'Sin experiencia con microservicios en produccion',
            'No maneja contenedores ni cloud',
          ],
          summary: 'Perfil con bases de Java pero orientado mas a frontend. Requiere validacion.',
        },
        created_at: '2025-06-10T11:00:00Z',
        updated_at: '2025-06-10T11:00:00Z',
        candidate: MOCK_CANDIDATES[3],
      },
      {
        id: 'pc-001-005',
        process_id: 'proc-001',
        candidate_id: 'cand-005',
        status: 'MATCHED',
        match_percentage: 72,
        match_category: 'MEDIUM',
        match_explanation: {
          strengths: [],
          gaps: [],
          summary: 'Pendiente de profiling.',
        },
        cv_match_percentage: 72,
        cv_match_category: 'MEDIUM',
        cv_match_explanation: {
          strengths: [
            'Experiencia con Python y Node.js como backend alternativo',
            'Buen manejo de bases de datos y SQL avanzado',
            'Proyecto de microservicios con Docker documentado',
          ],
          gaps: [
            'No tiene experiencia directa con Java/Spring Boot',
            'Kubernetes solo a nivel teorico',
          ],
          summary: 'Perfil de data engineering con algo de backend. El cambio de stack es el riesgo principal.',
        },
        created_at: '2025-06-10T12:00:00Z',
        updated_at: '2025-06-10T12:00:00Z',
        candidate: MOCK_CANDIDATES[4],
      },
      {
        id: 'pc-001-006',
        process_id: 'proc-001',
        candidate_id: 'cand-006',
        status: 'MATCHED',
        match_percentage: 62,
        match_category: 'MEDIUM',
        match_explanation: {
          strengths: [],
          gaps: [],
          summary: 'Pendiente de profiling.',
        },
        cv_match_percentage: 62,
        cv_match_category: 'MEDIUM',
        cv_match_explanation: {
          strengths: [
            'Experiencia con APIs y servicios web',
            'Conocimiento de Git y CI/CD basico',
          ],
          gaps: [
            'Perfil principalmente de datos, no backend de aplicaciones',
            'Sin mencion de Java ni Spring',
            'Sin experiencia con Kubernetes',
          ],
          summary: 'Perfil con gaps significativos para el rol. Podria ser candidata a futuro con formacion.',
        },
        created_at: '2025-06-10T13:00:00Z',
        updated_at: '2025-06-10T13:00:00Z',
        candidate: MOCK_CANDIDATES[5],
      },
      {
        id: 'pc-001-007',
        process_id: 'proc-001',
        candidate_id: 'cand-007',
        status: 'MATCHED',
        match_percentage: 58,
        match_category: 'MEDIUM',
        match_explanation: {
          strengths: [],
          gaps: [],
          summary: 'Pendiente de profiling.',
        },
        cv_match_percentage: 58,
        cv_match_category: 'MEDIUM',
        cv_match_explanation: {
          strengths: [
            'Perfil de liderazgo solido, podria encajar en rol hibrido',
            'Comunicacion y coordinacion de equipos tecnicos',
          ],
          gaps: [
            'Perfil de PM, no ingenieria de software',
            'Sin experiencia tecnica directa en Java o microservicios',
            'No aplica al rol de ingenieria tal como esta definido',
          ],
          summary: 'Perfil incorrecto para el rol. Seria mejor candidato para PM.',
          risk_flags: ['Perfil directivo sin experiencia de implementacion tecnica'],
        },
        created_at: '2025-06-10T14:00:00Z',
        updated_at: '2025-06-10T14:00:00Z',
        candidate: MOCK_CANDIDATES[6],
      },
    ],
    LOW: [
      {
        id: 'pc-001-008',
        process_id: 'proc-001',
        candidate_id: 'cand-008',
        status: 'DISCARDED',
        match_percentage: 22,
        match_category: 'LOW',
        match_explanation: {
          strengths: [],
          gaps: [],
          summary: 'Descartado por baja afinidad con el rol.',
        },
        cv_match_percentage: 22,
        cv_match_category: 'LOW',
        cv_match_explanation: {
          strengths: ['Perfil creativo y orientado al usuario'],
          gaps: [
            'Perfil 100% de diseno UX/UI, no tiene background tecnico de ingenieria',
            'Sin mencion de programacion ni lenguajes',
            'No aplica para rol de Backend',
          ],
          summary: 'Perfil completamente diferente al requerido. No hay afinidad con el rol tecnico.',
          risk_flags: ['Postulacion a rol incorrecto'],
        },
        created_at: '2025-06-10T15:00:00Z',
        updated_at: '2025-06-10T15:00:00Z',
        candidate: MOCK_CANDIDATES[7],
      },
      {
        id: 'pc-001-010',
        process_id: 'proc-001',
        candidate_id: 'cand-010',
        status: 'MATCHED',
        match_percentage: 35,
        match_category: 'LOW',
        match_explanation: {
          strengths: [],
          gaps: [],
          summary: 'Pendiente de profiling.',
        },
        cv_match_percentage: 35,
        cv_match_category: 'LOW',
        cv_match_explanation: {
          strengths: ['Conocimiento de conceptos de APIs REST'],
          gaps: [
            'Perfil principalmente frontend (React/Angular)',
            'Sin experiencia en Java ni en backend de aplicaciones empresariales',
            'No cumple ninguno de los must-have del rol',
          ],
          summary: 'Candidata frontend sin experiencia en el stack requerido para este rol senior de backend.',
        },
        created_at: '2025-06-10T16:00:00Z',
        updated_at: '2025-06-10T16:00:00Z',
        candidate: MOCK_CANDIDATES[9],
      },
      {
        id: 'pc-001-003',
        process_id: 'proc-001',
        candidate_id: 'cand-003',
        status: 'MATCHED',
        match_percentage: 41,
        match_category: 'LOW',
        match_explanation: {
          strengths: [],
          gaps: [],
          summary: 'Pendiente de profiling.',
        },
        cv_match_percentage: 41,
        cv_match_category: 'LOW',
        cv_match_explanation: {
          strengths: [
            'Conocimiento de TypeScript y programacion orientada a objetos',
            'Experiencia con APIs REST en Next.js',
          ],
          gaps: [
            'Perfil frontend, sin experiencia real en Java o Spring',
            'No menciona contenedores ni cloud en el CV',
            'No tiene el nivel de seniority requerido para backend distribuido',
          ],
          summary: 'Candidato fuerte en frontend pero con gap significativo para backend senior.',
        },
        created_at: '2025-06-10T17:00:00Z',
        updated_at: '2025-06-10T17:00:00Z',
        candidate: MOCK_CANDIDATES[2],
      },
    ],
    LOADED: [],
    PARSING: [],
  },
  'proc-002': {
    HIGH: [
      {
        id: 'pc-002-003',
        process_id: 'proc-002',
        candidate_id: 'cand-003',
        status: 'SELECTED_FOR_PROFILING',
        match_percentage: 93,
        match_category: 'HIGH',
        match_explanation: {
          strengths: [
            'Dominio total de React hooks avanzados y patrones de composicion',
            'TypeScript generics y utility types descritos con claridad',
            'Ha construido sistemas de diseno desde cero con Storybook',
          ],
          gaps: ['Menciona Redux clasico, no Redux Toolkit especificamente'],
          summary: 'Candidato sobresaliente para el rol. La entrevista confirma conocimiento profundo y capacidad de comunicacion.',
        },
        cv_match_percentage: 88,
        cv_match_category: 'HIGH',
        cv_match_explanation: {
          strengths: [
            '5 anos con React y TypeScript en proyectos de produccion',
            'Next.js App Router y Server Components',
            'Testing con Jest, RTL y Cypress documentado',
          ],
          gaps: ['No menciona Zustand, solo Redux en el CV'],
          summary: 'Perfil muy completo para el rol frontend. Cumple todos los must-have.',
        },
        created_at: '2025-06-12T09:00:00Z',
        updated_at: '2025-06-16T10:00:00Z',
        candidate: MOCK_CANDIDATES[2],
      },
      {
        id: 'pc-002-010',
        process_id: 'proc-002',
        candidate_id: 'cand-010',
        status: 'SELECTED_FOR_PROFILING',
        match_percentage: 79,
        match_category: 'HIGH',
        match_explanation: {
          strengths: [
            'Buena comprension de React y TypeScript',
            'Ha trabajado con disenadores usando Figma',
          ],
          gaps: [
            'Testing menos maduro que lo esperado',
            'Zustand nuevo para ella, solo Redux en produccion',
          ],
          summary: 'Candidata con buen nivel. La entrevista revela solidez en lo core aunque con brechas en testing avanzado.',
        },
        cv_match_percentage: 76,
        cv_match_category: 'HIGH',
        cv_match_explanation: {
          strengths: [
            '3 anos con React, experiencia en proyectos de producto',
            'Tailwind CSS y CSS moderno',
            'Git y flujos de trabajo colaborativo',
          ],
          gaps: [
            'Testing con Jest documentado pero poca profundidad',
            'Next.js mencionado brevemente',
          ],
          summary: 'Perfil frontend solido para nivel semi-senior. Cumple los must-have principales.',
        },
        created_at: '2025-06-12T10:00:00Z',
        updated_at: '2025-06-16T11:00:00Z',
        candidate: MOCK_CANDIDATES[9],
      },
    ],
    MEDIUM: [
      {
        id: 'pc-002-004',
        process_id: 'proc-002',
        candidate_id: 'cand-004',
        status: 'MATCHED',
        match_percentage: 65,
        match_category: 'MEDIUM',
        match_explanation: { strengths: [], gaps: [], summary: 'Pendiente de profiling.' },
        cv_match_percentage: 65,
        cv_match_category: 'MEDIUM',
        cv_match_explanation: {
          strengths: ['4 anos con React y Vue, conocimiento de TypeScript', 'Experiencia con Figma y trabajo con disenadores'],
          gaps: ['Vue es su stack principal, React secundario', 'Testing muy basico en el CV'],
          summary: 'Candidata con buen potencial pero con React como secundario respecto a Vue.',
        },
        created_at: '2025-06-12T11:00:00Z',
        updated_at: '2025-06-12T11:00:00Z',
        candidate: MOCK_CANDIDATES[3],
      },
    ],
    LOW: [
      {
        id: 'pc-002-001',
        process_id: 'proc-002',
        candidate_id: 'cand-001',
        status: 'MATCHED',
        match_percentage: 28,
        match_category: 'LOW',
        match_explanation: { strengths: [], gaps: [], summary: 'Pendiente de profiling.' },
        cv_match_percentage: 28,
        cv_match_category: 'LOW',
        cv_match_explanation: {
          strengths: ['Conocimiento de Java y APIs'],
          gaps: ['Perfil 100% backend, sin experiencia en React ni frontend moderno', 'No aplica al rol'],
          summary: 'Candidato backend aplicando a rol frontend. Gap total en el stack requerido.',
          risk_flags: ['Postulacion a rol incorrecto'],
        },
        created_at: '2025-06-12T12:00:00Z',
        updated_at: '2025-06-12T12:00:00Z',
        candidate: MOCK_CANDIDATES[0],
      },
    ],
    LOADED: [],
    PARSING: [],
  },
  'proc-003': {
    HIGH: [],
    MEDIUM: [],
    LOW: [],
    LOADED: [
      {
        id: 'pc-003-005',
        process_id: 'proc-003',
        candidate_id: 'cand-005',
        status: 'PARSING',
        match_percentage: 0,
        match_category: 'LOW',
        match_explanation: { strengths: [], gaps: [], summary: 'En procesamiento.' },
        cv_match_percentage: 0,
        cv_match_category: 'LOW',
        cv_match_explanation: { strengths: [], gaps: [], summary: 'CV en cola de procesamiento.' },
        created_at: '2025-06-17T08:00:00Z',
        updated_at: '2025-06-17T08:00:00Z',
        candidate: MOCK_CANDIDATES[4],
      },
      {
        id: 'pc-003-006',
        process_id: 'proc-003',
        candidate_id: 'cand-006',
        status: 'PARSING',
        match_percentage: 0,
        match_category: 'LOW',
        match_explanation: { strengths: [], gaps: [], summary: 'En procesamiento.' },
        cv_match_percentage: 0,
        cv_match_category: 'LOW',
        cv_match_explanation: { strengths: [], gaps: [], summary: 'CV en cola de procesamiento.' },
        created_at: '2025-06-17T08:05:00Z',
        updated_at: '2025-06-17T08:05:00Z',
        candidate: MOCK_CANDIDATES[5],
      },
    ],
    PARSING: [],
  },
};

// ─── Profiling Runs ───────────────────────────────────────────────────────────
export const MOCK_PROFILING_RUNS: Record<string, ProfilingRun[]> = {
  'proc-001': [
    {
      id: 'run-001-001',
      process_id: 'proc-001',
      candidate_id: 'cand-001',
      question_set_id: 'qs-001',
      status: 'COMPLETED',
      call_attempts: 1,
      advancement_prob: 'HIGH',
      transcription_url: '/transcriptions/run-001-001.json',
      profiling_eval: {
        overall_score: 91,
        communication: 95,
        technical_depth: 88,
        culture_fit: 92,
        notable_phrases: ['Lideramos la migracion de 12 servicios a Kubernetes en 3 meses', 'Prefiero code reviews como mecanismo de aprendizaje en equipo'],
      },
      created_at: '2025-06-15T10:00:00Z',
      updated_at: '2025-06-15T10:42:00Z',
      candidate: MOCK_CANDIDATES[0],
    },
    {
      id: 'run-001-002',
      process_id: 'proc-001',
      candidate_id: 'cand-002',
      question_set_id: 'qs-001',
      status: 'COMPLETED',
      call_attempts: 1,
      advancement_prob: 'HIGH',
      transcription_url: '/transcriptions/run-001-002.json',
      profiling_eval: {
        overall_score: 84,
        communication: 90,
        technical_depth: 80,
        culture_fit: 85,
        notable_phrases: ['Optimice las queries y redujimos la latencia de 800ms a 120ms', 'Me adapto rapido a nuevas tecnologias cuando tengo el contexto claro'],
      },
      created_at: '2025-06-15T11:00:00Z',
      updated_at: '2025-06-15T11:38:00Z',
      candidate: MOCK_CANDIDATES[1],
    },
    {
      id: 'run-001-009',
      process_id: 'proc-001',
      candidate_id: 'cand-009',
      question_set_id: 'qs-001',
      status: 'COMPLETED',
      call_attempts: 2,
      advancement_prob: 'MEDIUM',
      transcription_url: '/transcriptions/run-001-009.json',
      profiling_eval: {
        overall_score: 80,
        communication: 78,
        technical_depth: 76,
        culture_fit: 88,
        notable_phrases: ['Tengo proyectos personales en Kubernetes, aun no en produccion', 'Aprendo muy rapido cuando me dan el espacio para hacerlo'],
      },
      created_at: '2025-06-15T14:00:00Z',
      updated_at: '2025-06-15T14:35:00Z',
      candidate: MOCK_CANDIDATES[8],
    },
  ],
  'proc-002': [
    {
      id: 'run-002-003',
      process_id: 'proc-002',
      candidate_id: 'cand-003',
      question_set_id: 'qs-002',
      status: 'COMPLETED',
      call_attempts: 1,
      advancement_prob: 'HIGH',
      transcription_url: '/transcriptions/run-002-003.json',
      profiling_eval: {
        overall_score: 93,
        communication: 95,
        technical_depth: 92,
        culture_fit: 90,
      },
      created_at: '2025-06-16T10:00:00Z',
      updated_at: '2025-06-16T10:40:00Z',
      candidate: MOCK_CANDIDATES[2],
    },
    {
      id: 'run-002-010',
      process_id: 'proc-002',
      candidate_id: 'cand-010',
      question_set_id: 'qs-002',
      status: 'NO_ANSWER',
      call_attempts: 3,
      advancement_prob: undefined,
      created_at: '2025-06-16T11:00:00Z',
      updated_at: '2025-06-16T13:00:00Z',
      candidate: MOCK_CANDIDATES[9],
    },
  ],
};

// ─── Question Sets ────────────────────────────────────────────────────────────
export const MOCK_QUESTION_SETS: QuestionSet[] = [
  {
    id: 'qs-001',
    name: 'Backend Senior - Tecnico + Valores',
    description: 'Cuestionario para validar profundidad tecnica en arquitecturas distribuidas y alineacion cultural para roles de ingenieria senior.',
    version: 3,
    status: 'ACTIVE',
    created_by: 'user-001',
    created_at: '2025-05-15T10:00:00Z',
    updated_at: '2025-06-01T14:00:00Z',
    questions: [
      {
        id: 'q-001-01',
        question_set_id: 'qs-001',
        order_index: 0,
        text: 'Describeme un proyecto en el que hayas tenido que disenar una arquitectura de microservicios desde cero. Que decisiones tomaste y por que?',
        type: 'OPEN',
        positive_keywords: ['microservicios', 'escalabilidad', 'dominio', 'bounded context', 'api gateway', 'event driven', 'kafka', 'desacoplamiento'],
        risk_keywords: ['monolito', 'no se', 'nunca lo hice', 'solo segui lo que habia'],
        weight: 10,
        is_critical: true,
        eval_criteria: 'Buscar mencion de patrones DDD o arquitectura hexagonal. El candidato debe poder justificar decisiones de diseño con trade-offs claros, no solo describir tecnologias.',
      },
      {
        id: 'q-001-02',
        question_set_id: 'qs-001',
        order_index: 1,
        text: 'Cuentame sobre una situacion en la que tuviste que optimizar el rendimiento de un servicio en produccion bajo presion. Que herramientas usaste y cual fue el resultado?',
        type: 'OPEN',
        positive_keywords: ['profiling', 'flamegraph', 'APM', 'latencia', 'throughput', 'cache', 'indices', 'query plan', 'monitorizacion', 'metricas'],
        risk_keywords: ['reinicie el servidor', 'no recuerdo bien', 'pedi ayuda a alguien mas', 'nunca tuve ese problema'],
        weight: 8,
        is_critical: true,
        eval_criteria: 'Valorar metodologia de debugging sistematica: hipotesis, medicion, intervencion, validacion. La mencion de herramientas concretas (New Relic, Datadog, JProfiler) es una senal positiva.',
      },
      {
        id: 'q-001-03',
        question_set_id: 'qs-001',
        order_index: 2,
        text: 'Como manejas el desacuerdo tecnico con un companero de equipo o lider cuando estas convencido de que tu solucion es mejor?',
        type: 'OPEN',
        positive_keywords: ['datos', 'prototipo', 'documentar', 'escuchar', 'benchmark', 'consenso', 'adc', 'architectural decision', 'pragmatico'],
        risk_keywords: ['impongo', 'escalo al manager', 'me resigno sin decir nada', 'evito el conflicto', 'siempre tengo razon'],
        weight: 7,
        is_critical: false,
        eval_criteria: 'Evaluar inteligencia emocional y madurez tecnica. El candidato ideal propone experimentos o datos como mecanismo de resolucion, no solo argumentacion.',
      },
      {
        id: 'q-001-04',
        question_set_id: 'qs-001',
        order_index: 3,
        text: 'En una escala del 1 al 10, como calificarias tu experiencia con Kubernetes en entornos de produccion? Describe el caso de uso mas complejo que hayas manejado.',
        type: 'SCALE',
        positive_keywords: ['deployments', 'statefulsets', 'hpa', 'ingress', 'helm', 'istio', 'namespaces', 'resource limits', 'liveness probe', 'rolling update'],
        risk_keywords: ['solo tutoriales', 'minikube local', 'basico', 'otro equipo lo manejaba', 'nunca lo use en produccion'],
        weight: 9,
        is_critical: true,
        eval_criteria: 'Puntaje de 7+ con descripcion de caso real. Menos de 6 con incapacidad de describir un caso concreto es un riesgo dado el JD.',
      },
      {
        id: 'q-001-05',
        question_set_id: 'qs-001',
        order_index: 4,
        text: 'Que es lo que mas valoras en un equipo de ingenieria y por que?',
        type: 'OPEN',
        positive_keywords: ['documentacion', 'code review', 'retrospectivas', 'seguridad psicologica', 'autonomia', 'aprendizaje', 'calidad', 'feedback', 'colaboracion'],
        risk_keywords: ['que me dejen solo', 'sin reuniones', 'que no me molesten', 'solo resultados sin importar como'],
        weight: 5,
        is_critical: false,
        eval_criteria: 'Evaluar fit cultural. Candidatos que mencionan feedback continuo, documentacion y code reviews como valores indican madurez de equipo.',
      },
    ],
  },
  {
    id: 'qs-002',
    name: 'Frontend React - Tecnico + Ownership',
    description: 'Cuestionario para validar conocimiento avanzado de React, TypeScript, testing y culture de ownership en desarrolladores frontend.',
    version: 1,
    status: 'ACTIVE',
    created_by: 'user-001',
    created_at: '2025-06-02T10:00:00Z',
    updated_at: '2025-06-02T10:00:00Z',
    questions: [
      {
        id: 'q-002-01',
        question_set_id: 'qs-002',
        order_index: 0,
        text: 'Explica como funciona el sistema de reconciliacion de React y como impacta las decisiones de arquitectura de componentes en una aplicacion grande.',
        type: 'OPEN',
        positive_keywords: ['virtual dom', 'fiber', 'reconciliacion', 'memoizacion', 'usememo', 'usecallback', 'keys', 'render', 'splitting', 'lazy load'],
        risk_keywords: ['no se exactamente', 'react lo hace solo', 'nunca tuve ese problema', 'solo uso componentes'],
        weight: 9,
        is_critical: true,
        eval_criteria: 'Candidato debe mencionar la importancia de keys, cuándo usar memo/useMemo/useCallback y cómo las decisiones de estructura impactan el re-render tree.',
      },
      {
        id: 'q-002-02',
        question_set_id: 'qs-002',
        order_index: 1,
        text: 'Cuentame sobre un bug critico en produccion que hayas causado y como lo resolviste. Que aprendiste de esa experiencia?',
        type: 'OPEN',
        positive_keywords: ['postmortem', 'rollback', 'hotfix', 'monitorizacion', 'alerta', 'aprendizaje', 'documentar', 'prevencion', 'tests', 'responsabilidad'],
        risk_keywords: ['nunca he causado bugs', 'otro lo soluciono', 'no recuerdo', 'culpe a alguien mas', 'me estrese mucho y no hice nada'],
        weight: 7,
        is_critical: false,
        eval_criteria: 'Valorar ownership y madurez. El candidato que admite errores con claridad y describe acciones preventivas posteriores muestra una mentalidad de crecimiento.',
      },
      {
        id: 'q-002-03',
        question_set_id: 'qs-002',
        order_index: 2,
        text: 'Como defines y mantienes la estrategia de testing en un proyecto frontend? Que proporcion de unit, integration y e2e consideras optima?',
        type: 'OPEN',
        positive_keywords: ['trofeo de testing', 'integracion', 'rtl', 'jest', 'cypress', 'playwright', 'cobertura', 'falsos negativos', 'confidence', 'user behavior'],
        risk_keywords: ['solo unit tests', 'no testeo mucho', 'qa lo hace', 'sin tiempo para tests', 'testing es opcional'],
        weight: 8,
        is_critical: true,
        eval_criteria: 'Buscar mencion del Testing Trophy de Kent C. Dodds o razonamiento similar. La respuesta correcta prioriza integration tests sobre unit tests puros.',
      },
    ],
  },
];

// ─── Metricas ─────────────────────────────────────────────────────────────────
export const MOCK_METRICS: MetricsDashboard = {
  total_cost_usd: 47.83,
  cost_by_process: [
    { process_id: 'proc-001', process_name: 'Ingeniero Backend Senior', total_cost: 22.40, candidate_count: 10 },
    { process_id: 'proc-002', process_name: 'Desarrollador Frontend React', total_cost: 14.20, candidate_count: 7 },
    { process_id: 'proc-003', process_name: 'Data Engineer - Pipeline Analytics', total_cost: 8.13, candidate_count: 4 },
    { process_id: 'proc-004', process_name: 'Product Manager - Fintech', total_cost: 2.40, candidate_count: 0 },
    { process_id: 'proc-005', process_name: 'UX/UI Product Designer', total_cost: 0.70, candidate_count: 0 },
  ],
  cost_by_user: [
    { user_id: 'user-001', user_name: 'Recruiter Principal', total_cost: 39.00 },
    { user_id: 'user-002', user_name: 'TA Leader', total_cost: 8.83 },
  ],
  cost_by_operation: [
    { operation_type: 'CV_MATCH', total_cost: 18.50, count: 21 },
    { operation_type: 'JD_PARSE', total_cost: 3.20, count: 5 },
    { operation_type: 'VOICE_PROFILING', total_cost: 21.40, count: 6 },
    { operation_type: 'PROFILE_EXTRACT', total_cost: 4.73, count: 21 },
  ],
  daily_costs: [
    { date: '2025-06-10', cost: 8.40 },
    { date: '2025-06-11', cost: 4.20 },
    { date: '2025-06-12', cost: 11.30 },
    { date: '2025-06-13', cost: 6.10 },
    { date: '2025-06-14', cost: 3.80 },
    { date: '2025-06-15', cost: 9.20 },
    { date: '2025-06-16', cost: 4.83 },
  ],
};

// ─── AI Models ────────────────────────────────────────────────────────────────
export const MOCK_AI_MODELS: AIModelConfig[] = [
  { id: 'model-001', task_type: 'CV_MATCH',        provider: 'ANTHROPIC', model_name: 'claude-sonnet-4-6',      is_active: true,  updated_by: 'admin', updated_at: '2025-06-01T00:00:00Z' },
  { id: 'model-002', task_type: 'CV_MATCH',        provider: 'OPENAI',    model_name: 'gpt-4o',                 is_active: false, updated_by: 'admin', updated_at: '2025-05-20T00:00:00Z' },
  { id: 'model-003', task_type: 'JD_PARSE',        provider: 'ANTHROPIC', model_name: 'claude-haiku-4-5',       is_active: true,  updated_by: 'admin', updated_at: '2025-06-01T00:00:00Z' },
  { id: 'model-004', task_type: 'VOICE_PROFILING', provider: 'ELEVENLABS', model_name: 'eleven_turbo_v2',       is_active: true,  updated_by: 'admin', updated_at: '2025-06-01T00:00:00Z' },
  { id: 'model-005', task_type: 'PROFILE_EXTRACT', provider: 'ANTHROPIC', model_name: 'claude-haiku-4-5',       is_active: true,  updated_by: 'admin', updated_at: '2025-06-01T00:00:00Z' },
];

export const MOCK_AI_PROMPTS: AIPrompt[] = [
  {
    id: 'prompt-001',
    task_type: 'CV_MATCH',
    version_name: 'v2 - Match con explicacion detallada',
    system_prompt_text: `Eres un evaluador experto en reclutamiento tecnico. Tu tarea es analizar el CV de un candidato y compararlo con el Job Description proporcionado.

Debes:
1. Identificar cuales must-have cumple el candidato (con evidencia del CV)
2. Identificar cuales nice-to-have cumple
3. Verificar si hay deal-breakers
4. Calcular un porcentaje de match ponderado (must_have: 60%, nice_to_have: 25%, inferencias: 15%)
5. Categorizar: HIGH (>=80%), MEDIUM (60-79%), LOW (<60%)
6. Redactar una explicacion con strengths, gaps y risk_flags si aplica

Responde siempre en JSON valido con la estructura definida.`,
    is_active: true,
    updated_by: 'admin',
    updated_at: '2025-06-01T00:00:00Z',
  },
  {
    id: 'prompt-002',
    task_type: 'JD_PARSE',
    version_name: 'v1 - Extraccion estructurada de JD',
    system_prompt_text: `Eres un especialista en analisis de perfiles de cargo. Extrae la informacion del Job Description en formato estructurado.

Clasifica cada requisito en:
- must_have: requisitos innegociables
- nice_to_have: requisitos deseables pero no bloqueantes
- deal_breakers: condiciones que descalifican al candidato automaticamente

Asigna pesos relativos a cada categoria segun la importancia implicita en el texto.
Responde siempre en JSON valido.`,
    is_active: true,
    updated_by: 'admin',
    updated_at: '2025-06-01T00:00:00Z',
  },
];
