/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CambiarContrasenaRouteImport } from './routes/cambiar-contrasena'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSetsRouteImport } from './routes/app.sets'
import { Route as AppProfilingRouteImport } from './routes/app.profiling'
import { Route as AppEquipoRouteImport } from './routes/app.equipo'
import { Route as AppCostosRouteImport } from './routes/app.costos'
import { Route as AppBuscarRouteImport } from './routes/app.buscar'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppSetsIndexRouteImport } from './routes/app.sets.index'
import { Route as AppSetsNuevoRouteImport } from './routes/app.sets.nuevo'
import { Route as AppSetsIdRouteImport } from './routes/app.sets.$id'
import { Route as AppProcesosNuevoRouteImport } from './routes/app.procesos.nuevo'
import { Route as AppProcesosIdRouteImport } from './routes/app.procesos.$id'

const CambiarContrasenaRoute = CambiarContrasenaRouteImport.update({
  id: '/cambiar-contrasena',
  path: '/cambiar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSetsRoute = AppSetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilingRoute = AppProfilingRouteImport.update({
  id: '/profiling',
  path: '/profiling',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipoRoute = AppEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AppRoute,
} as any)
const AppCostosRoute = AppCostosRouteImport.update({
  id: '/costos',
  path: '/costos',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSetsIndexRoute = AppSetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSetsRoute,
} as any)
const AppSetsNuevoRoute = AppSetsNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppSetsRoute,
} as any)
const AppSetsIdRoute = AppSetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSetsRoute,
} as any)
const AppProcesosNuevoRoute = AppProcesosNuevoRouteImport.update({
  id: '/procesos/nuevo',
  path: '/procesos/nuevo',
  getParentRoute: () => AppRoute,
} as any)
const AppProcesosIdRoute = AppProcesosIdRouteImport.update({
  id: '/procesos/$id',
  path: '/procesos/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/app/admin': typeof AppAdminRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/costos': typeof AppCostosRoute
  '/app/equipo': typeof AppEquipoRoute
  '/app/profiling': typeof AppProfilingRoute
  '/app/sets': typeof AppSetsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/procesos/$id': typeof AppProcesosIdRoute
  '/app/procesos/nuevo': typeof AppProcesosNuevoRoute
  '/app/sets/$id': typeof AppSetsIdRoute
  '/app/sets/nuevo': typeof AppSetsNuevoRoute
  '/app/sets/': typeof AppSetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/app/admin': typeof AppAdminRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/costos': typeof AppCostosRoute
  '/app/equipo': typeof AppEquipoRoute
  '/app/profiling': typeof AppProfilingRoute
  '/app': typeof AppIndexRoute
  '/app/procesos/$id': typeof AppProcesosIdRoute
  '/app/procesos/nuevo': typeof AppProcesosNuevoRoute
  '/app/sets/$id': typeof AppSetsIdRoute
  '/app/sets/nuevo': typeof AppSetsNuevoRoute
  '/app/sets': typeof AppSetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/cambiar-contrasena': typeof CambiarContrasenaRoute
  '/app/admin': typeof AppAdminRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/costos': typeof AppCostosRoute
  '/app/equipo': typeof AppEquipoRoute
  '/app/profiling': typeof AppProfilingRoute
  '/app/sets': typeof AppSetsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/procesos/$id': typeof AppProcesosIdRoute
  '/app/procesos/nuevo': typeof AppProcesosNuevoRoute
  '/app/sets/$id': typeof AppSetsIdRoute
  '/app/sets/nuevo': typeof AppSetsNuevoRoute
  '/app/sets/': typeof AppSetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cambiar-contrasena'
    | '/app/admin'
    | '/app/buscar'
    | '/app/costos'
    | '/app/equipo'
    | '/app/profiling'
    | '/app/sets'
    | '/app/'
    | '/app/procesos/$id'
    | '/app/procesos/nuevo'
    | '/app/sets/$id'
    | '/app/sets/nuevo'
    | '/app/sets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cambiar-contrasena'
    | '/app/admin'
    | '/app/buscar'
    | '/app/costos'
    | '/app/equipo'
    | '/app/profiling'
    | '/app'
    | '/app/procesos/$id'
    | '/app/procesos/nuevo'
    | '/app/sets/$id'
    | '/app/sets/nuevo'
    | '/app/sets'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/cambiar-contrasena'
    | '/app/admin'
    | '/app/buscar'
    | '/app/costos'
    | '/app/equipo'
    | '/app/profiling'
    | '/app/sets'
    | '/app/'
    | '/app/procesos/$id'
    | '/app/procesos/nuevo'
    | '/app/sets/$id'
    | '/app/sets/nuevo'
    | '/app/sets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CambiarContrasenaRoute: typeof CambiarContrasenaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cambiar-contrasena': {
      id: '/cambiar-contrasena'
      path: '/cambiar-contrasena'
      fullPath: '/cambiar-contrasena'
      preLoaderRoute: typeof CambiarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sets': {
      id: '/app/sets'
      path: '/sets'
      fullPath: '/app/sets'
      preLoaderRoute: typeof AppSetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profiling': {
      id: '/app/profiling'
      path: '/profiling'
      fullPath: '/app/profiling'
      preLoaderRoute: typeof AppProfilingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipo': {
      id: '/app/equipo'
      path: '/equipo'
      fullPath: '/app/equipo'
      preLoaderRoute: typeof AppEquipoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/costos': {
      id: '/app/costos'
      path: '/costos'
      fullPath: '/app/costos'
      preLoaderRoute: typeof AppCostosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buscar': {
      id: '/app/buscar'
      path: '/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sets/': {
      id: '/app/sets/'
      path: '/'
      fullPath: '/app/sets/'
      preLoaderRoute: typeof AppSetsIndexRouteImport
      parentRoute: typeof AppSetsRoute
    }
    '/app/sets/nuevo': {
      id: '/app/sets/nuevo'
      path: '/nuevo'
      fullPath: '/app/sets/nuevo'
      preLoaderRoute: typeof AppSetsNuevoRouteImport
      parentRoute: typeof AppSetsRoute
    }
    '/app/sets/$id': {
      id: '/app/sets/$id'
      path: '/$id'
      fullPath: '/app/sets/$id'
      preLoaderRoute: typeof AppSetsIdRouteImport
      parentRoute: typeof AppSetsRoute
    }
    '/app/procesos/nuevo': {
      id: '/app/procesos/nuevo'
      path: '/procesos/nuevo'
      fullPath: '/app/procesos/nuevo'
      preLoaderRoute: typeof AppProcesosNuevoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procesos/$id': {
      id: '/app/procesos/$id'
      path: '/procesos/$id'
      fullPath: '/app/procesos/$id'
      preLoaderRoute: typeof AppProcesosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSetsRouteChildren {
  AppSetsIdRoute: typeof AppSetsIdRoute
  AppSetsNuevoRoute: typeof AppSetsNuevoRoute
  AppSetsIndexRoute: typeof AppSetsIndexRoute
}

const AppSetsRouteChildren: AppSetsRouteChildren = {
  AppSetsIdRoute: AppSetsIdRoute,
  AppSetsNuevoRoute: AppSetsNuevoRoute,
  AppSetsIndexRoute: AppSetsIndexRoute,
}

const AppSetsRouteWithChildren =
  AppSetsRoute._addFileChildren(AppSetsRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBuscarRoute: typeof AppBuscarRoute
  AppCostosRoute: typeof AppCostosRoute
  AppEquipoRoute: typeof AppEquipoRoute
  AppProfilingRoute: typeof AppProfilingRoute
  AppSetsRoute: typeof AppSetsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppProcesosIdRoute: typeof AppProcesosIdRoute
  AppProcesosNuevoRoute: typeof AppProcesosNuevoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBuscarRoute: AppBuscarRoute,
  AppCostosRoute: AppCostosRoute,
  AppEquipoRoute: AppEquipoRoute,
  AppProfilingRoute: AppProfilingRoute,
  AppSetsRoute: AppSetsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppProcesosIdRoute: AppProcesosIdRoute,
  AppProcesosNuevoRoute: AppProcesosNuevoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CambiarContrasenaRoute: CambiarContrasenaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
